"""Render the About page team grid + bio dialogs from _team/team.json.

    python _team/build_team.py

Replaces everything between the TEAM:START / TEAM:END comments in about.html.
Bios are written into the page (inside closed <dialog>s) so they stay in the HTML.
"""
import json
from html import escape
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "about.html"
START = "<!-- TEAM:START (generated by _team/build_team.py from _team/team.json; do not edit by hand) -->"
END = "<!-- TEAM:END -->"

LINKEDIN_PATH = "M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"


def display_name(m):
    return f"{m['name']}, {m['credentials']}" if m.get("credentials") else m["name"]


def initials(m):
    parts = [p for p in m["name"].replace(".", " ").split() if p[0].isupper()]
    return (parts[0][0] + parts[-1][0]) if len(parts) > 1 else parts[0][0]


def title_html(title):
    # <wbr> after "/" lets long compound titles wrap cleanly; the text itself is unchanged.
    return escape(title).replace("/", "/<wbr>")


def photo_html(m, cls, lazy=True):
    name = escape(display_name(m))
    if not m.get("photo"):
        return f'<div class="{cls} is-initials" role="img" aria-label="{name}"><span aria-hidden="true">{initials(m)}</span></div>'
    loading = ' loading="lazy"' if lazy else ""
    return (
        f'<div class="{cls}"><img src="{escape(m["photo"])}" alt="{name}" width="480" height="600"'
        f'{loading} decoding="async" style="object-position: {escape(m.get("focal") or "50% 30%")}"></div>'
    )


def linkedin_html(m, cls):
    if not m.get("linkedin"):
        return ""
    return (
        f'<a class="{cls}" href="{escape(m["linkedin"])}" target="_blank" rel="noopener noreferrer" '
        f'aria-label="{escape(display_name(m))} on LinkedIn"><svg width="18" height="18" viewBox="0 0 24 24" '
        f'fill="currentColor" aria-hidden="true"><path d="{LINKEDIN_PATH}"/></svg></a>'
    )


def card(m, i):
    name = escape(display_name(m))
    slug = m["slug"]
    button = ""
    if m.get("bio"):
        button = (
            f'<button type="button" class="member-bio-btn" data-bio="{slug}" aria-haspopup="dialog" '
            f'aria-controls="bio-{slug}">Read bio<span class="visually-hidden"> for {name}</span></button>'
        )
    link = linkedin_html(m, "member-linkedin")
    actions = f'\n{i}        <div class="member-actions">{button}{link}</div>' if (button or link) else ""
    return (
        f'{i}<article class="team-member" id="{slug}">\n'
        f'{i}    {photo_html(m, "member-photo")}\n'
        f'{i}    <div class="member-body">\n'
        f'{i}        <h3 class="member-name">{name}</h3>\n'
        f'{i}        <p class="member-title">{title_html(m["title"])}</p>'
        f'{actions}\n'
        f'{i}    </div>\n'
        f'{i}</article>'
    )


def dialog(m, i):
    slug = m["slug"]
    paras = "\n".join(f"{i}            <p>{escape(p, quote=False)}</p>" for p in m["bio"])
    link = linkedin_html(m, "member-linkedin")
    link = f"\n{i}        {link}" if link else ""
    return (
        f'{i}<dialog class="bio-dialog" id="bio-{slug}" data-slug="{slug}" aria-labelledby="bio-{slug}-name">\n'
        f'{i}    <button type="button" class="bio-dialog-close" aria-label="Close bio">'
        f'<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">'
        f'<line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button>\n'
        f'{i}    {photo_html(m, "bio-dialog-photo")}\n'
        f'{i}    <div class="bio-dialog-content">\n'
        f'{i}        <h2 class="bio-dialog-name" id="bio-{slug}-name">{escape(display_name(m))}</h2>\n'
        f'{i}        <p class="bio-dialog-title">{title_html(m["title"])}</p>\n'
        f'{i}        <div class="bio-dialog-text">\n{paras}\n{i}        </div>{link}\n'
        f'{i}    </div>\n'
        f'{i}</dialog>'
    )


def main():
    members = [m for m in json.loads((ROOT / "_team" / "team.json").read_text(encoding="utf-8"))["members"]
               if not m.get("hidden")]
    slugs = [m["slug"] for m in members]
    assert len(slugs) == len(set(slugs)), "duplicate slug"

    ind = " " * 16
    block = "\n".join([
        START,
        f'{ind}<div class="team-grid">',
        *[card(m, ind + "    ") for m in members],
        f"{ind}</div>",
        *[dialog(m, ind) for m in members if m.get("bio")],
        f"{ind}{END}",
    ])

    html = PAGE.read_text(encoding="utf-8")
    a, b = html.index(START), html.index(END) + len(END)
    PAGE.write_text(html[:a] + block + html[b:], encoding="utf-8", newline="\n")
    print(f"about.html: {len(members)} cards, {sum(1 for m in members if m.get('bio'))} bios")


if __name__ == "__main__":
    main()
